### ISSUE TITLE
Record values of other observables

### ISSUE THREAD

**Issue by jonrkarr** [biosimulators/Biosimulators_PySCeS#5]
- [x] Constant species
- [x] Parameters
- [ ] Species and parameters set via assignment rules
- [x] Reaction fluxes
- [x] Compartment sizes

**Comment by jmrohwer** [comment]
Assignment rules can now be tracked. See https://github.com/PySCeS/pysces/issues/57#issuecomment-1128605118. Fixed in latest PySCeS Release ([1.0.2](https://github.com/PySCeS/pysces/releases/tag/1.0.2)).

**Comment by jmrohwer** [comment]
This continues the discussion [from here](https://github.com/biosimulators/Biosimulators_PySCeS/issues/7#issuecomment-2106978379) where certain model outputs are not recorded.

The unrecorded variables are all assignment rules. In fact they are recorded by PySCeS, so it is a wrapper issue. Staying with Biomodels 297. I've had a brief look at the wrapper code. The wrapper records the simulation results here: https://github.com/biosimulators/Biosimulators_PySCeS/blob/2d97929994747fd30b5684393bb850839955b5eb/biosimulators_pysces/core.py#L158

@luciansmith I have verified that this array contains all the simulation data including the assignment rules, in fact it is the same data as in the `model.sim` DataFrame (refer [here](https://github.com/biosimulators/Biosimulators_PySCeS/issues/7#issuecomment-2106978379)), just presented as a numpy array with or without labels.

It therefore has to do with filtering of the model attributes which as far as I can see happens here:
https://github.com/biosimulators/Biosimulators_PySCeS/blob/2d97929994747fd30b5684393bb850839955b5eb/biosimulators_pysces/core.py#L309-L310

The rules are not part `dynamic_ids` nor `fixed_ids` as far as I can tell. I know too little about the wrapper implementation in general to be able to tell how this is generally done, or what would need to change for them to be recorded.

The assignment and rate rules are in a dictionary `mod.__rules__` where the ID of each rule is the key. For each key (rule) the value is another dictionary with the following keys:
- name  (the SBML ID of the rule, this is the same as the key in the top-level dict)
- formula
- type (assignment or rate)
- symbols (list of symbols in the rule)
- code string (formula adapted with class references so it can be executed in PySCeS)

Hopefully this will give you sufficient info to track this down further. Unfortunately I don't have time in the coming weeks to work on this myself.

**Comment by luciansmith** [comment]
Thanks for the analysis!  Now that the pipeline works again, I can tackle this.

**Comment by luciansmith** [comment]
And, this now works!  And the PySCeS wrapper can now handle 711 of the biomodels, waaaay up from the previous 241.  That section was indeed key!  So thanks.

**Comment by jmrohwer** [comment]
I'm happy you were able to track this down :smiley:
